apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  port: {{ .Values.port | b64enc }}
  dbUser: {{ .Values.dbUser | b64enc }}
  databasePassword: {{ .Values.databasePassword | b64enc }}
  dbHost: {{ .Values.dbHost | b64enc }}
  database: {{ .Values.database | b64enc }}
  dbPort: {{ .Values.dbPort | b64enc }}
  nodeEnv: {{ .Values.nodeEnv | b64enc }}





